In [1]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn import datasets
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [2]:
#cargar datos 
df = pd.read_csv('DatosFinales.csv', sep=';', decimal=',')
df = df.set_index('Date')
df

Google Trends   Hashrate     Tweets  Bitcoin Mining Profitability  \
Date                                                                            
2018-01-24        0.00000  18.691603   1.513460                      9.158578   
2018-01-25       -6.31789  -3.172174  20.557616                    -22.756307   
2018-01-26        0.00000  -2.290384 -13.352529                      4.415544   
2018-01-27        0.00000   2.186828  -3.904755                     -5.099308   
2018-01-28        0.00000  -7.034714   0.825950                     12.101774   
...                   ...        ...        ...                           ...   
2019-12-27        0.00000  -9.318675  -5.764566                    -16.142344   
2019-12-28        0.00000 -22.055082  -6.303997                      5.675282   
2019-12-29        0.00000   4.831291   1.464136                     -0.692044   
2019-12-30        0.00000  10.182248  -3.302881                      5.406722   
2019-12-31        0.00000   2.378053   0.366400                    -11.860574   

            Bitcoin Block Time  Bitcoin Sent from Addresses  \
Date                                                          
2018-01-24           -5.822516                   -11.694390   
2018-01-25           -4.910489                   -16.016052   
2018-01-26           -3.529014                    17.409128   
2018-01-27            4.727876                    15.851871   
2018-01-28           -7.579294                     4.898545   
...                        ...                          ...   
2019-12-27          -15.837823                    22.046524   
2019-12-28            0.641202                     1.946010   
2019-12-29          -12.063077                    -2.066696   
2019-12-30            4.059709                    -4.224686   
2019-12-31           16.702700                     1.748684   

            10-Year Breakeven Inflation Rate  Trade Weighted US Dollar Index  \
Date                                                                           
2018-01-24                          0.990107                       -0.538480   
2018-01-25                          0.000000                       -0.533548   
2018-01-26                          0.000000                        0.000000   
2018-01-27                          0.000000                        0.000000   
2018-01-28                          0.491401                        0.000000   
...                                      ...                             ...   
2019-12-27                          0.000000                        0.000000   
2019-12-28                          1.149438                        0.000000   
2019-12-29                          0.569802                       -0.000260   
2019-12-30                          0.566574                        0.091946   
2019-12-31                          0.000000                       -0.054310   

            CBOE Volatility Index  Wilshire 5000 Total Market Full Cap Index  \
Date                                                                           
2018-01-24               2.794593                                   0.000000   
2018-01-25              13.770574                                   0.000000   
2018-01-26               0.000000                                   0.000000   
2018-01-27               0.000000                                   0.906386   
2018-01-28               0.000000                                  -0.208438   
...                           ...                                        ...   
2019-12-27               0.000000                                   0.072884   
2019-12-28               0.000000                                   0.026490   
2019-12-29               1.228014                                   0.449261   
2019-12-30               2.332233                                   0.486619   
2019-12-31              -0.637961                                   0.091797   

            Dow Jones Industrial Average Index  \
Date  

In [3]:
from sklearn.model_selection import train_test_split

#define predictor and response variables
X = df.drop("Bitcoin sign change", axis=1)
y = df["Bitcoin sign change"]

# División en train y test
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify = y, test_size = 0.2)

# División del set de entrenamiento en entrenamiento y validación
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, stratify = y_train, test_size = 0.2)

### Kernel lineal

In [19]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train);

In [20]:
y_pred = svclassifier.predict(X_test)

In [21]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))


[[34 35]
 [34 39]]
              precision    recall  f1-score   support

           0       0.50      0.49      0.50        69
           1       0.53      0.53      0.53        73

    accuracy                           0.51       142
   macro avg       0.51      0.51      0.51       142
weighted avg       0.51      0.51      0.51       142



### Kernel polinomial

In [22]:
svclassifier1 = SVC(kernel='poly', degree=8)
svclassifier1.fit(X_train, y_train);

In [23]:
y_pred1 = svclassifier1.predict(X_test)

In [24]:
print(confusion_matrix(y_test,y_pred1))
print(classification_report(y_test,y_pred1))


[[59 10]
 [60 13]]
              precision    recall  f1-score   support

           0       0.50      0.86      0.63        69
           1       0.57      0.18      0.27        73

    accuracy                           0.51       142
   macro avg       0.53      0.52      0.45       142
weighted avg       0.53      0.51      0.44       142



### Kernel Gaussiano

In [17]:
svclassifier2 = SVC(kernel='rbf')
svclassifier2.fit(X_train, y_train);

In [26]:
y_pred2 = svclassifier2.predict(X_test)

In [27]:
print(confusion_matrix(y_test,y_pred2))
print(classification_report(y_test,y_pred2))

[[34 35]
 [30 43]]
              precision    recall  f1-score   support

           0       0.53      0.49      0.51        69
           1       0.55      0.59      0.57        73

    accuracy                           0.54       142
   macro avg       0.54      0.54      0.54       142
weighted avg       0.54      0.54      0.54       142



### Kernel Sigmoid

In [29]:
svclassifier3 = SVC(kernel='sigmoid')
svclassifier3.fit(X_train, y_train);

In [31]:
y_pred3 = svclassifier3.predict(X_test)

In [32]:
print(confusion_matrix(y_test,y_pred3))
print(classification_report(y_test,y_pred3))

[[23 46]
 [38 35]]
              precision    recall  f1-score   support

           0       0.38      0.33      0.35        69
           1       0.43      0.48      0.45        73

    accuracy                           0.41       142
   macro avg       0.40      0.41      0.40       142
weighted avg       0.41      0.41      0.41       142



https://intellipaat.com/blog/tutorial/machine-learning-tutorial/svm-algorithm-in-python/